import express from 'express';
import { fileURLToPath } from 'url';
import path from 'path';
import { GoogleGenAI, Type } from '@google/genai';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(express.json());

// Initialize GoogleGenAI SDK server-side
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || '',
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// API endpoint for OpenManus Autonomous Agent Execution
app.post('/api/agent/run', async (req, res) => {
  try {
    const { prompt, mode = 'Website' } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      // If no API key is provided, provide a robust autonomous simulation
      return res.json({
        success: true,
        simulation: true,
        plan: [
          { text: `Analyze requirements for: "${prompt}"`, status: 'done' },
          { text: 'Perform wide research and gather best practices', status: 'done' },
          { text: 'Design system architecture and file structure', status: 'done' },
          { text: 'Execute code generation & browser automation', status: 'done' },
          { text: 'Run verification tests and performance audit', status: 'done' }
        ],
        logs: [
          { time: new Date().toLocaleTimeString(), message: `Task initialized in cloud container: "${prompt}"`, type: 'info' },
          { time: new Date().toLocaleTimeString(), message: 'Executing autonomous planning via OpenManus engine...', type: 'info' },
          { time: new Date().toLocaleTimeString(), message: 'Generated architecture: index.html, App.tsx, styles.css, server.ts', type: 'success' },
          { time: new Date().toLocaleTimeString(), message: 'Task successfully completed with 0 errors.', type: 'success' }
        ],
        files: [
          { name: 'index.html', icon: '📄', size: '2.4 KB', content: '<!DOCTYPE html>\n<html>\n<head><title>OpenManus App</title></head>\n<body>\n  <div id="root"></div>\n</body>\n</html>' },
          { name: 'App.tsx', icon: '⚛️', size: '5.1 KB', content: 'export default function App() {\n  return <div className="p-8 font-sans"><h1>OpenManus Generated App</h1><p>Prompt: ' + prompt + '</p></div>;\n}' },
          { name: 'server.ts', icon: '🚀', size: '3.8 KB', content: 'import express from "express";\nconst app = express();\napp.listen(3000, () => console.log("Server running"));' },
          { name: 'README.md', icon: '📖', size: '1.2 KB', content: '# Generated by OpenManus\nTask: ' + prompt }
        ]
      });
    }

    // Use Gemini to generate structured plan and code
    const systemInstruction = `You are OpenManus, an autonomous general AI agent. The user has given a task prompt. 
You must analyze the task, generate a structured 5-step execution plan, activity logs, and code files (such as index.html, App.tsx, server.ts, README.md) that fully solve the user's prompt. 
Return your response strictly in JSON format matching this schema:
{
  "plan": [{"text": "...", "status": "done"}],
  "logs": [{"time": "...", "message": "...", "type": "info|success|error"}],
  "files": [{"name": "...", "icon": "...", "size": "...", "content": "..."}]
}`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: `Task: ${prompt}\nMode: ${mode}`,
      config: {
        systemInstruction,
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            plan: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  text: { type: Type.STRING },
                  status: { type: Type.STRING }
                },
                required: ['text', 'status']
              }
            },
            logs: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  time: { type: Type.STRING },
                  message: { type: Type.STRING },
                  type: { type: Type.STRING }
                },
                required: ['time', 'message', 'type']
              }
            },
            files: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  name: { type: Type.STRING },
                  icon: { type: Type.STRING },
                  size: { type: Type.STRING },
                  content: { type: Type.STRING }
                },
                required: ['name', 'icon', 'size', 'content']
              }
            }
          },
          required: ['plan', 'logs', 'files']
        }
      }
    });

    const result = JSON.parse(response.text || '{}');
    res.json({ success: true, ...result });

  } catch (error: any) {
    console.error('Agent execution error:', error);
    res.status(500).json({ error: error.message || 'Internal server error during agent execution' });
  }
});

// Vite middleware integration in development
if (process.env.NODE_ENV !== 'production') {
  const { createServer: createViteServer } = await import('vite');
  const vite = await createViteServer({
    server: { middlewareMode: true },
    appType: 'spa',
  });
  app.use(vite.middlewares);
} else {
  const distPath = path.join(__dirname, 'dist');
  app.use(express.static(distPath));
  app.get('*', (req, res) => {
    res.sendFile(path.join(distPath, 'index.html'));
  });
}

const PORT = Number(process.env.PORT || 3000);
app.listen(PORT, '0.0.0.0', () => {
  console.log(`OpenManus server running on http://localhost:${PORT}`);
});
